# Generated by Django 4.1.5 on 2023-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('about', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Pharmaceutical', 'Pharmaceutical'), ('Entertainment', 'Entertainment')], max_length=64)),
                ('founded', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
